/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffShellRouteImport } from './routes/_staffShell'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DeliveryAddressRouteImport } from './routes/delivery-address'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PaymentResultRouteImport } from './routes/payment-result'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSignupRouteImport } from './routes/admin.signup'
import { Route as StaffShellAdminIndexRouteImport } from './routes/_staffShell.admin.index'
import { Route as StaffShellAdminAppsRouteImport } from './routes/_staffShell.admin.apps'
import { Route as StaffShellAdminBranchesRouteImport } from './routes/_staffShell.admin.branches'
import { Route as StaffShellAdminCashbackRouteImport } from './routes/_staffShell.admin.cashback'
import { Route as StaffShellAdminCouponsRouteImport } from './routes/_staffShell.admin.coupons'
import { Route as StaffShellAdminCustomersRouteImport } from './routes/_staffShell.admin.customers'
import { Route as StaffShellAdminLoyaltyRouteImport } from './routes/_staffShell.admin.loyalty'
import { Route as StaffShellAdminMarketingToolsRouteImport } from './routes/_staffShell.admin.marketing-tools'
import { Route as StaffShellAdminNewOrderRouteImport } from './routes/_staffShell.admin.new-order'
import { Route as StaffShellAdminOrdersRouteImport } from './routes/_staffShell.admin.orders'
import { Route as StaffShellAdminPaymentsRouteImport } from './routes/_staffShell.admin.payments'
import { Route as StaffShellAdminProductsRouteImport } from './routes/_staffShell.admin.products'
import { Route as StaffShellAdminRefundsRouteImport } from './routes/_staffShell.admin.refunds'
import { Route as StaffShellAdminReportsRouteImport } from './routes/_staffShell.admin.reports'
import { Route as StaffShellAdminSettingsRouteImport } from './routes/_staffShell.admin.settings'
import { Route as StaffShellAdminStaffRouteImport } from './routes/_staffShell.admin.staff'
import { Route as StaffShellAdminCustomersCustomerIdRouteImport } from './routes/_staffShell.admin.customers.$customerId'
import { Route as StaffShellAdminCustomersGroupsRouteImport } from './routes/_staffShell.admin.customers.groups'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffShellRoute = StaffShellRouteImport.update({
  id: '/_staffShell',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryAddressRoute = DeliveryAddressRouteImport.update({
  id: '/delivery-address',
  path: '/delivery-address',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment-result',
  path: '/payment-result',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffShellAdminIndexRoute = StaffShellAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminAppsRoute = StaffShellAdminAppsRouteImport.update({
  id: '/admin/apps',
  path: '/admin/apps',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminBranchesRoute = StaffShellAdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminCashbackRoute = StaffShellAdminCashbackRouteImport.update({
  id: '/admin/cashback',
  path: '/admin/cashback',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminCouponsRoute = StaffShellAdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminCustomersRoute =
  StaffShellAdminCustomersRouteImport.update({
    id: '/admin/customers',
    path: '/admin/customers',
    getParentRoute: () => StaffShellRoute,
  } as any)
const StaffShellAdminLoyaltyRoute = StaffShellAdminLoyaltyRouteImport.update({
  id: '/admin/loyalty',
  path: '/admin/loyalty',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminMarketingToolsRoute =
  StaffShellAdminMarketingToolsRouteImport.update({
    id: '/admin/marketing-tools',
    path: '/admin/marketing-tools',
    getParentRoute: () => StaffShellRoute,
  } as any)
const StaffShellAdminNewOrderRoute = StaffShellAdminNewOrderRouteImport.update({
  id: '/admin/new-order',
  path: '/admin/new-order',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminOrdersRoute = StaffShellAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminPaymentsRoute = StaffShellAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminProductsRoute = StaffShellAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminRefundsRoute = StaffShellAdminRefundsRouteImport.update({
  id: '/admin/refunds',
  path: '/admin/refunds',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminReportsRoute = StaffShellAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminSettingsRoute = StaffShellAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminStaffRoute = StaffShellAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => StaffShellRoute,
} as any)
const StaffShellAdminCustomersCustomerIdRoute =
  StaffShellAdminCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => StaffShellAdminCustomersRoute,
  } as any)
const StaffShellAdminCustomersGroupsRoute =
  StaffShellAdminCustomersGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => StaffShellAdminCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/delivery-address': typeof DeliveryAddressRoute
  '/menu': typeof MenuRoute
  '/payment-result': typeof PaymentResultRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/apps': typeof StaffShellAdminAppsRoute
  '/admin/branches': typeof StaffShellAdminBranchesRoute
  '/admin/cashback': typeof StaffShellAdminCashbackRoute
  '/admin/coupons': typeof StaffShellAdminCouponsRoute
  '/admin/customers': typeof StaffShellAdminCustomersRouteWithChildren
  '/admin/loyalty': typeof StaffShellAdminLoyaltyRoute
  '/admin/marketing-tools': typeof StaffShellAdminMarketingToolsRoute
  '/admin/new-order': typeof StaffShellAdminNewOrderRoute
  '/admin/orders': typeof StaffShellAdminOrdersRoute
  '/admin/payments': typeof StaffShellAdminPaymentsRoute
  '/admin/products': typeof StaffShellAdminProductsRoute
  '/admin/refunds': typeof StaffShellAdminRefundsRoute
  '/admin/reports': typeof StaffShellAdminReportsRoute
  '/admin/settings': typeof StaffShellAdminSettingsRoute
  '/admin/staff': typeof StaffShellAdminStaffRoute
  '/admin/': typeof StaffShellAdminIndexRoute
  '/admin/customers/$customerId': typeof StaffShellAdminCustomersCustomerIdRoute
  '/admin/customers/groups': typeof StaffShellAdminCustomersGroupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/delivery-address': typeof DeliveryAddressRoute
  '/menu': typeof MenuRoute
  '/payment-result': typeof PaymentResultRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/apps': typeof StaffShellAdminAppsRoute
  '/admin/branches': typeof StaffShellAdminBranchesRoute
  '/admin/cashback': typeof StaffShellAdminCashbackRoute
  '/admin/coupons': typeof StaffShellAdminCouponsRoute
  '/admin/customers': typeof StaffShellAdminCustomersRouteWithChildren
  '/admin/loyalty': typeof StaffShellAdminLoyaltyRoute
  '/admin/marketing-tools': typeof StaffShellAdminMarketingToolsRoute
  '/admin/new-order': typeof StaffShellAdminNewOrderRoute
  '/admin/orders': typeof StaffShellAdminOrdersRoute
  '/admin/payments': typeof StaffShellAdminPaymentsRoute
  '/admin/products': typeof StaffShellAdminProductsRoute
  '/admin/refunds': typeof StaffShellAdminRefundsRoute
  '/admin/reports': typeof StaffShellAdminReportsRoute
  '/admin/settings': typeof StaffShellAdminSettingsRoute
  '/admin/staff': typeof StaffShellAdminStaffRoute
  '/admin': typeof StaffShellAdminIndexRoute
  '/admin/customers/$customerId': typeof StaffShellAdminCustomersCustomerIdRoute
  '/admin/customers/groups': typeof StaffShellAdminCustomersGroupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_staffShell': typeof StaffShellRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/delivery-address': typeof DeliveryAddressRoute
  '/menu': typeof MenuRoute
  '/payment-result': typeof PaymentResultRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/_staffShell/admin/apps': typeof StaffShellAdminAppsRoute
  '/_staffShell/admin/branches': typeof StaffShellAdminBranchesRoute
  '/_staffShell/admin/cashback': typeof StaffShellAdminCashbackRoute
  '/_staffShell/admin/coupons': typeof StaffShellAdminCouponsRoute
  '/_staffShell/admin/customers': typeof StaffShellAdminCustomersRouteWithChildren
  '/_staffShell/admin/loyalty': typeof StaffShellAdminLoyaltyRoute
  '/_staffShell/admin/marketing-tools': typeof StaffShellAdminMarketingToolsRoute
  '/_staffShell/admin/new-order': typeof StaffShellAdminNewOrderRoute
  '/_staffShell/admin/orders': typeof StaffShellAdminOrdersRoute
  '/_staffShell/admin/payments': typeof StaffShellAdminPaymentsRoute
  '/_staffShell/admin/products': typeof StaffShellAdminProductsRoute
  '/_staffShell/admin/refunds': typeof StaffShellAdminRefundsRoute
  '/_staffShell/admin/reports': typeof StaffShellAdminReportsRoute
  '/_staffShell/admin/settings': typeof StaffShellAdminSettingsRoute
  '/_staffShell/admin/staff': typeof StaffShellAdminStaffRoute
  '/_staffShell/admin/': typeof StaffShellAdminIndexRoute
  '/_staffShell/admin/customers/$customerId': typeof StaffShellAdminCustomersCustomerIdRoute
  '/_staffShell/admin/customers/groups': typeof StaffShellAdminCustomersGroupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/delivery-address'
    | '/menu'
    | '/payment-result'
    | '/admin/login'
    | '/admin/signup'
    | '/admin/apps'
    | '/admin/branches'
    | '/admin/cashback'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/loyalty'
    | '/admin/marketing-tools'
    | '/admin/new-order'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/'
    | '/admin/customers/$customerId'
    | '/admin/customers/groups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/delivery-address'
    | '/menu'
    | '/payment-result'
    | '/admin/login'
    | '/admin/signup'
    | '/admin/apps'
    | '/admin/branches'
    | '/admin/cashback'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/loyalty'
    | '/admin/marketing-tools'
    | '/admin/new-order'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin'
    | '/admin/customers/$customerId'
    | '/admin/customers/groups'
  id:
    | '__root__'
    | '/'
    | '/_staffShell'
    | '/checkout'
    | '/delivery-address'
    | '/menu'
    | '/payment-result'
    | '/admin/login'
    | '/admin/signup'
    | '/_staffShell/admin/apps'
    | '/_staffShell/admin/branches'
    | '/_staffShell/admin/cashback'
    | '/_staffShell/admin/coupons'
    | '/_staffShell/admin/customers'
    | '/_staffShell/admin/loyalty'
    | '/_staffShell/admin/marketing-tools'
    | '/_staffShell/admin/new-order'
    | '/_staffShell/admin/orders'
    | '/_staffShell/admin/payments'
    | '/_staffShell/admin/products'
    | '/_staffShell/admin/refunds'
    | '/_staffShell/admin/reports'
    | '/_staffShell/admin/settings'
    | '/_staffShell/admin/staff'
    | '/_staffShell/admin/'
    | '/_staffShell/admin/customers/$customerId'
    | '/_staffShell/admin/customers/groups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaffShellRoute: typeof StaffShellRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  DeliveryAddressRoute: typeof DeliveryAddressRoute
  MenuRoute: typeof MenuRoute
  PaymentResultRoute: typeof PaymentResultRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSignupRoute: typeof AdminSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staffShell': {
      id: '/_staffShell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-address': {
      id: '/delivery-address'
      path: '/delivery-address'
      fullPath: '/delivery-address'
      preLoaderRoute: typeof DeliveryAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-result': {
      id: '/payment-result'
      path: '/payment-result'
      fullPath: '/payment-result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staffShell/admin/': {
      id: '/_staffShell/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof StaffShellAdminIndexRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/apps': {
      id: '/_staffShell/admin/apps'
      path: '/admin/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof StaffShellAdminAppsRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/branches': {
      id: '/_staffShell/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof StaffShellAdminBranchesRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/cashback': {
      id: '/_staffShell/admin/cashback'
      path: '/admin/cashback'
      fullPath: '/admin/cashback'
      preLoaderRoute: typeof StaffShellAdminCashbackRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/coupons': {
      id: '/_staffShell/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof StaffShellAdminCouponsRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/customers': {
      id: '/_staffShell/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof StaffShellAdminCustomersRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/loyalty': {
      id: '/_staffShell/admin/loyalty'
      path: '/admin/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof StaffShellAdminLoyaltyRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/marketing-tools': {
      id: '/_staffShell/admin/marketing-tools'
      path: '/admin/marketing-tools'
      fullPath: '/admin/marketing-tools'
      preLoaderRoute: typeof StaffShellAdminMarketingToolsRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/new-order': {
      id: '/_staffShell/admin/new-order'
      path: '/admin/new-order'
      fullPath: '/admin/new-order'
      preLoaderRoute: typeof StaffShellAdminNewOrderRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/orders': {
      id: '/_staffShell/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof StaffShellAdminOrdersRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/payments': {
      id: '/_staffShell/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof StaffShellAdminPaymentsRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/products': {
      id: '/_staffShell/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof StaffShellAdminProductsRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/refunds': {
      id: '/_staffShell/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof StaffShellAdminRefundsRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/reports': {
      id: '/_staffShell/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof StaffShellAdminReportsRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/settings': {
      id: '/_staffShell/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof StaffShellAdminSettingsRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/staff': {
      id: '/_staffShell/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof StaffShellAdminStaffRouteImport
      parentRoute: typeof StaffShellRoute
    }
    '/_staffShell/admin/customers/$customerId': {
      id: '/_staffShell/admin/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof StaffShellAdminCustomersCustomerIdRouteImport
      parentRoute: typeof StaffShellAdminCustomersRoute
    }
    '/_staffShell/admin/customers/groups': {
      id: '/_staffShell/admin/customers/groups'
      path: '/groups'
      fullPath: '/admin/customers/groups'
      preLoaderRoute: typeof StaffShellAdminCustomersGroupsRouteImport
      parentRoute: typeof StaffShellAdminCustomersRoute
    }
  }
}

interface StaffShellAdminCustomersRouteChildren {
  StaffShellAdminCustomersCustomerIdRoute: typeof StaffShellAdminCustomersCustomerIdRoute
  StaffShellAdminCustomersGroupsRoute: typeof StaffShellAdminCustomersGroupsRoute
}

const StaffShellAdminCustomersRouteChildren: StaffShellAdminCustomersRouteChildren =
  {
    StaffShellAdminCustomersCustomerIdRoute:
      StaffShellAdminCustomersCustomerIdRoute,
    StaffShellAdminCustomersGroupsRoute: StaffShellAdminCustomersGroupsRoute,
  }

const StaffShellAdminCustomersRouteWithChildren =
  StaffShellAdminCustomersRoute._addFileChildren(
    StaffShellAdminCustomersRouteChildren,
  )

interface StaffShellRouteChildren {
  StaffShellAdminAppsRoute: typeof StaffShellAdminAppsRoute
  StaffShellAdminBranchesRoute: typeof StaffShellAdminBranchesRoute
  StaffShellAdminCashbackRoute: typeof StaffShellAdminCashbackRoute
  StaffShellAdminCouponsRoute: typeof StaffShellAdminCouponsRoute
  StaffShellAdminCustomersRoute: typeof StaffShellAdminCustomersRouteWithChildren
  StaffShellAdminLoyaltyRoute: typeof StaffShellAdminLoyaltyRoute
  StaffShellAdminMarketingToolsRoute: typeof StaffShellAdminMarketingToolsRoute
  StaffShellAdminNewOrderRoute: typeof StaffShellAdminNewOrderRoute
  StaffShellAdminOrdersRoute: typeof StaffShellAdminOrdersRoute
  StaffShellAdminPaymentsRoute: typeof StaffShellAdminPaymentsRoute
  StaffShellAdminProductsRoute: typeof StaffShellAdminProductsRoute
  StaffShellAdminRefundsRoute: typeof StaffShellAdminRefundsRoute
  StaffShellAdminReportsRoute: typeof StaffShellAdminReportsRoute
  StaffShellAdminSettingsRoute: typeof StaffShellAdminSettingsRoute
  StaffShellAdminStaffRoute: typeof StaffShellAdminStaffRoute
  StaffShellAdminIndexRoute: typeof StaffShellAdminIndexRoute
}

const StaffShellRouteChildren: StaffShellRouteChildren = {
  StaffShellAdminAppsRoute: StaffShellAdminAppsRoute,
  StaffShellAdminBranchesRoute: StaffShellAdminBranchesRoute,
  StaffShellAdminCashbackRoute: StaffShellAdminCashbackRoute,
  StaffShellAdminCouponsRoute: StaffShellAdminCouponsRoute,
  StaffShellAdminCustomersRoute: StaffShellAdminCustomersRouteWithChildren,
  StaffShellAdminLoyaltyRoute: StaffShellAdminLoyaltyRoute,
  StaffShellAdminMarketingToolsRoute: StaffShellAdminMarketingToolsRoute,
  StaffShellAdminNewOrderRoute: StaffShellAdminNewOrderRoute,
  StaffShellAdminOrdersRoute: StaffShellAdminOrdersRoute,
  StaffShellAdminPaymentsRoute: StaffShellAdminPaymentsRoute,
  StaffShellAdminProductsRoute: StaffShellAdminProductsRoute,
  StaffShellAdminRefundsRoute: StaffShellAdminRefundsRoute,
  StaffShellAdminReportsRoute: StaffShellAdminReportsRoute,
  StaffShellAdminSettingsRoute: StaffShellAdminSettingsRoute,
  StaffShellAdminStaffRoute: StaffShellAdminStaffRoute,
  StaffShellAdminIndexRoute: StaffShellAdminIndexRoute,
}

const StaffShellRouteWithChildren = StaffShellRoute._addFileChildren(
  StaffShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaffShellRoute: StaffShellRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  DeliveryAddressRoute: DeliveryAddressRoute,
  MenuRoute: MenuRoute,
  PaymentResultRoute: PaymentResultRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSignupRoute: AdminSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
